[package]
name = "the_next_week"
version = "0.1.0"
edition = "2021"

[dependencies]
mimalloc = "0.1"
image = "0.25"

vector3 = { path = "../vector3" }
utils = { path = "../utils" }

[[bin]]
name = "the_next_week"
path = "src/main.rs"

[[example]]
name = "test"
path = "examples/test.rs"
